# Some necessary info to create the JSON

era: 2022-2023

leptonFlavor: muon

etaBinEdges:
  - -2.4
  - -1.6
  - -1.0
  - 0.0
  - 1.0
  - 1.6
  - 2.4

flavMap:
  prompt: 0
  tauDecay: 1

ROOTFiles:
  prompt: SF_PromptMu_Run3_2022-2023.root
  tauDecay: SF_TauMu_Run3_2022-2023.root

