# Some necessary info to create the JSON

era: 2022-2023

leptonFlavor: electron

etaBinEdges:
  - -2.1
  - -1.6
  - -1.0
  - 0.0
  - 1.0
  - 1.6
  - 2.1

flavMap:
  prompt: 0
  tauDecay: 1

ROOTFiles:
  prompt: SF_PromptE_Run3_2022-2023.root
  tauDecay:  SF_TauE_Run3_2022-2023.root
